### ISSUE TITLE
How do i Bulid the engine 

### ISSUE THREAD

**Issue by Enchantedbooz** [CamtheKirby/VsDave-Modable#1]
How do i Bulid the engine #1

**Comment by CamLikesKirby** [comment]
Download haxe 4.2.5

You type cmd in the path bar

![image](https://github.com/CamtheKirby/VsDave-Modable/assets/92703353/ed0cb125-3993-44f4-9675-e085210108b5)

You install the Dependencies (Which is in the readme)

![image](https://github.com/CamtheKirby/VsDave-Modable/assets/92703353/321ccc06-a418-4220-bb90-fa2b96e61744)
you do this:

haxelib install put the dependency here then put the version like this:
haxelib install flixel 4.11.0
