### ISSUE TITLE
Compiling Issue 

### ISSUE THREAD

**Issue by ModdingGaming10** [CamtheKirby/VsDave-Modable#12]
C:/haxelib/flixel-addons/3,2,3/flixel/addons/transition/FlxTransitionableState.hx:6: characters 8-79 : Flixel-Addons is not compatible with flixel versions older than 5.3.0

**Comment by CamLikesKirby** [comment]
![image](https://github.com/user-attachments/assets/1f792a2f-84c8-4fcf-827a-c75c68ccfe21)
Make sure you have the right dependencies versions you can also use this:
https://github.com/CamtheKirby/VsDave-Modable/blob/main/Bulid.bat
