### ISSUE TITLE
Enhancement: make it more easier to use audio files because it's almost impossible to use them

### ISSUE THREAD

**Issue by daveandbambifan1234** [CamtheKirby/VsDave-Modable#2]
## What is your suggestion, and why should it be implemented?
![image](https://github.com/CamtheKirby/VsDave-Modable/assets/159091869/c5ded7ef-19e6-4a96-94e1-b9fa6f6bd137)

**Comment by CamLikesKirby** [comment]
Did you select your mod before doing this?
