### ISSUE TITLE
(question) can i use physic or js engine (physic but no botplay lag) charts?

### ISSUE THREAD

**Issue by Dimarar** [CamtheKirby/VsDave-Modable#3]
pls answer

**Comment by CamLikesKirby** [comment]
yes but some older version of psych engine might make it crash (idk about js engine)

**Comment by Dimarar** [comment]
and ye. what the frick admin mode doing?
![image](https://github.com/CamtheKirby/VsDave-Modable/assets/112246243/ba6efa94-0b8e-4bb0-9522-069b1e61bb80)

**Comment by CamLikesKirby** [comment]
It allows you to use botplay and practice mode on any song and other stuff (btw botplay and practice mode won't be in the admin menu next update)
