### ISSUE TITLE
Bug Report: idk why this happen

### ISSUE THREAD

**Issue by Dimarar** [CamtheKirby/VsDave-Modable#5]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
ok

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows 10 x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
"big update time" update

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
![image](https://github.com/CamtheKirby/VsDave-Modable/assets/112246243/5e1471dd-ff96-43de-a1d3-68a4a3331f6c)
if i know then i say
## Please describe your issue. Provide extensive detail and images if possible.
...

**Comment by moxie-coder** [comment]
make sure your not running the game in a path with special characters

**Comment by CamLikesKirby** [comment]
what where you trying to do
