### ISSUE TITLE
Bug Report: game crashing when song is loaded

### ISSUE THREAD

**Issue by Ivaniscool678** [CamtheKirby/VsDave-Modable#6]
when i opened my custom song as soon as the voice says "go!" the game crashes,i swear i did everything right

**Comment by CamLikesKirby** [comment]
Can you take a picture or video

**Comment by CamLikesKirby** [comment]
I think You need to add the settings folder copy the one from the test song folder to your folder and rename it to your-song-settings.json (https://github.com/CamtheKirby/VsDave-Modable/wiki/How-2-Add-Settings)

**Comment by Ivaniscool678** [comment]
Uploading 2024-08-17 18-45-02.mp4…

**Comment by Ivaniscool678** [comment]
https://github.com/user-attachments/assets/e9b138f4-aca2-4b86-af04-16a3df8ef52c

**Comment by CamLikesKirby** [comment]
Can you show me the folder the chart json is in

**Comment by CamLikesKirby** [comment]
also this might happen because the chart might not be compatible but I'm not sure yet

**Comment by Ivaniscool678** [comment]
i fixed it,i had to put the settings thing

**Comment by Ivaniscool678** [comment]
also theres another bug i found:whenever i press the arrow keys with no notes coming and i have no ghost tapping,the game crashes

**Comment by Ivaniscool678** [comment]
https://github.com/user-attachments/assets/6b3ea7a5-8104-40c6-b432-b256531cc015

**Comment by CamLikesKirby** [comment]
OK I'll work on that when I feel like working on this engine again

**Comment by Ivaniscool678** [comment]
okay
